// https://www.google.com/search?q=vscode+intellisense+typescript+enum&oq=vscode+intellisense+typescript+enum&aqs=chrome..69i57.5961j0j1&sourceid=chrome&ie=UTF-8
// https://code.visualstudio.com/docs/editor/intellisense
// https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant/60041791#60041791
// https://stackoverflow.com/questions/45141756/cant-intellisense-include-type-script-enum-reverse-mapping
// https://github.com/microsoft/TypeScript/issues/38486
// https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/hover.ts
// https://github.com/Microsoft/vscode/issues/30386
// https://code.visualstudio.com/api/references/vscode-api
// https://www.google.com/search?q=vs+code+intellisense+hover&oq=vs+code+intellisense+hover&aqs=chrome..69i57.4417j0j1&sourceid=chrome&ie=UTF-8
// https://blog.logrocket.com/writing-readable-code-with-typescript-enums-a84864f340e9/
// https://code.visualstudio.com/api/language-extensions/programmatic-language-features
// https://www.google.com/search?q=can+you+change+the+typescript+version+programatically&oq=can+you+change+the+typescript+version+programatically&aqs=chrome..69i57.8189j0j1&sourceid=chrome&ie=UTF-8
// https://www.google.com/search?q=set+typescript+version+vscode+api&oq=set+type&aqs=chrome.0.69i59l2j69i57j69i60.1760j0j1&sourceid=chrome&ie=UTF-8
// https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions
// https://www.google.com/search?q=npm+package+to+navigate+directories&oq=npm+package+to+navigate+directories&aqs=chrome..69i57j69i64.6798j0j1&sourceid=chrome&ie=UTF-8
// https://www.npmjs.com/search?q=directory%20walk&page=2
// https://www.npmjs.com/search?q=directory-traversal
// https://www.npmjs.com/package/traverse-folders
// https://www.google.com/search?q=npm+traverse+directories&oq=npm+traverse+directories&aqs=chrome..69i57j69i64.7094j0j1&sourceid=chrome&ie=UTF-8
// https://code.visualstudio.com/api
// https://code.visualstudio.com/api/extension-guides/virtual-documents
// https://www.google.com/search?q=get+path+of+file+in+view&oq=get+path+of+file+in+view&aqs=chrome..69i57.6654j0j1&sourceid=chrome&ie=UTF-8
// https://www.google.com/search?q=nodejspath&oq=nodejspath&aqs=chrome..69i57.4033j0j1&sourceid=chrome&ie=UTF-8
// https://github.com/CoenraadS/BracketPair/blob/develop/src/extension.ts
// https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer
// https://code.visualstudio.com/api/references/extension-manifest
// https://github.com/microsoft/vscode/issues/80056
// https://github.com/Microsoft/vscode/issues/58470
// https://code.visualstudio.com/api/advanced-topics/extension-host
// https://code.visualstudio.com/api/get-started/your-first-extension
// https://github.com/reduckted/GitWebLinks/blob/master/vscode/src/repository-finder.ts
// https://github.com/reduckted/GitWebLinks/blob/master/vscode/src/commands/index.ts
// https://github.com/reduckted/GitWebLinks/blob/master/vscode/src/commands/index.ts
// https://marketplace.visualstudio.com/items?itemName=Dang.package-json-helper
// https://marketplace.visualstudio.com/items?itemName=ldd-vs-code.better-package-json
// https://marketplace.visualstudio.com/items?itemName=loiane.ts-extension-pack
// https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero
// https://www.google.com/search?q=typescript+version+extension+vscode&oq=typescript+version+extension+vscode&aqs=chrome..69i57.5573j0j1&sourceid=chrome&ie=UTF-8
// https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions
// https://github.com/sveltejs/language-tools/issues/1045
// https://github.com/microsoft/vscode/issues/116503
// https://www.google.com/search?q=use+package.json+version+of+typescript+in+vs+code&sxsrf=APq-WBu4SHM8LRPYm-qUqrYk0_aQ0f3oRQ%3A1643667399132&ei=x1_4Yem7B4-D8gKZiaioDw&ved=0ahUKEwipu9Cbgt31AhWPgVwKHZkECvUQ4dUDCA4&uact=5&oq=use+package.json+version+of+typescript+in+vs+code&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQjwRYoxRg-BVoBHACeACAAYsBiAHaCZIBBDEzLjGYAQCgAQHIAQjAAQE&sclient=gws-wiz
// https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it
// https://github.com/CoenraadS/BracketPair#readme
// https://github.com/microsoft/vscode/issues
